version: "3.8"

services:
  inventory_db:
    container_name: inventory_db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: inventory
      MYSQL_USER: lazaro
      MYSQL_PASSWORD: lazaro
      MYSQL_ROOT_PASSWORD: sofia
    ports:
      - 3306:3306
    networks:
      inventory-net:

  inventory_app:
    container_name: inventory_app
    build: .
    ports:
      - 8080:8080
    depends_on:
      - inventory_db
    environment:
      - DB_URL=jdbc:mysql://inventory_db:3306/inventory?ssl-enabled=false&autoReconnect=true&connectTimeout=60000
      - DB_USER=lazaro
      - DB_PASS=lazaro
      - IMG_BASE_URL=http://localhost:8080/api/v1/item/image/
    networks:
      inventory-net:

networks:
  inventory-net: